### ISSUE TITLE
Create a visual part for Categories

### ISSUE THREAD

**Issue by t0t0cas** [ci2-ipt/SearchEngine_SIGQ#12]
### What is the objective of this issue?
Create a table for categories.

---
### Do you have any idea how this could be done, or what could happen?
Create a table for people can create and watch the table of categories.

---

**Comment by renatopanda** [comment]
Regarding the visual part, as stated yesterday since you all are using bootstrap 5, you should use and abuse bootstrap classes. This means understanding how bootstrap works, namely:
* Container or container-fluid classes
* How the breakpoints work (responsiveness)
* Grid system and columns

Using these, you create the main layout under application.html.erb (you can even break it in partials). Then you can use all the BS5 components as needed, from navbars to tables, buttons, forms and so on inside each view.

If you are not used to it (BS5) please spend a few hours reading the documentation (or video tutorial) first.

PS: You can also ask Rui for tips, he is using it too.
